apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: mongodb
spec:
  tls:
  - hosts:
    - world-demo.westus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: world-demo.westus.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: staticwebservice
          servicePort: 80
